import {
  AUTH_EVENTS,
  ORDER_EVENTS,
  PRODUCT_EVENTS,
  CHECKOUT_EVENTS,
  APP_EVENTS
} from './'
import {
  // PROVIDER_NAMES,
  ALL_PROVIDERS,
  ProviderList
} from '../constants/providerNames'

export const ALL_EVENT_PROVIDER_MAP: {
  [key: string]: ProviderList // 👈 This allows any string key
} = {
  // Auth Events
  [AUTH_EVENTS.USER_SIGNED_UP]: ALL_PROVIDERS,
  [AUTH_EVENTS.USER_SIGNED_IN]: ALL_PROVIDERS,
  [AUTH_EVENTS.USER_LOGGED_OUT]: ALL_PROVIDERS,
  [AUTH_EVENTS.USER_PROFILE_UPDATED]: ALL_PROVIDERS,
  [AUTH_EVENTS.USER_DEVICES]: ALL_PROVIDERS,

  // Product Events
  [PRODUCT_EVENTS.PRODUCT_VIEWED]: ALL_PROVIDERS,
  [PRODUCT_EVENTS.PRODUCT_ADDED_TO_CART]: ALL_PROVIDERS,
  [PRODUCT_EVENTS.PRODUCT_REMOVED_FROM_CART]: ALL_PROVIDERS,

  // Order Events
  [ORDER_EVENTS.ORDER_PLACED]: ALL_PROVIDERS,
  [ORDER_EVENTS.ORDER_FAILED]: ALL_PROVIDERS,
  [ORDER_EVENTS.ORDER_CANCELLED]: ALL_PROVIDERS,
  [ORDER_EVENTS.RETURN_REQUESTED]: ALL_PROVIDERS,

  // Checkout Events
  [CHECKOUT_EVENTS.CHECKOUT_STARTED]: ALL_PROVIDERS,
  [CHECKOUT_EVENTS.CHECKOUT_ABANDONED]: ALL_PROVIDERS,
  [CHECKOUT_EVENTS.PAYMENT_SUCCESSFUL]: ALL_PROVIDERS,
  [CHECKOUT_EVENTS.PAYMENT_FAILED]: ALL_PROVIDERS,

  // [ORDER_EVENTS.ORDER_FAILED]: [PROVIDER_NAMES.SEGMENT] - Example for customization

  // APP Events
  [APP_EVENTS.SEARCH_PERFORMED]: ALL_PROVIDERS,
  [APP_EVENTS.CATEGORY_BROWSED]: ALL_PROVIDERS,
  [APP_EVENTS.DOCTOR_CONSULTATION]: ALL_PROVIDERS,
  [APP_EVENTS.PRESCRIPTION_ENQUIRY]: ALL_PROVIDERS,
  [APP_EVENTS.PRESCRIPTION_ENQUIRY_SEARCH]: ALL_PROVIDERS,
  [APP_EVENTS.NOTIFICATION_CLICKED]: ALL_PROVIDERS
}
